CREATE DATABASE celery;
CREATE DATABASE operational;
CREATE DATABASE operational_test;

CREATE USER celery WITH ENCRYPTED PASSWORD 'celery';
CREATE USER coo WITH ENCRYPTED PASSWORD 'chief-of-operations';

ALTER DATABASE celery OWNER TO celery;
ALTER DATABASE operational OWNER TO coo;
ALTER DATABASE operational_test OWNER TO coo;

GRANT ALL PRIVILEGES ON DATABASE celery TO celery;
GRANT ALL PRIVILEGES ON DATABASE operational TO coo;
GRANT ALL PRIVILEGES ON DATABASE operational_test TO coo;

\c celery
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO celery;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO celery;

\c operational
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO coo;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO coo;

\c operational_test
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO coo;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO coo;
